source "https://rubygems.org"

gem 'react-rails'

gem "jsbundling-rails", "~> 1.3"

gem "activestorage", "~> 8.1"

gem "sprockets-rails", "~> 3.5"

gem "vite_ruby", "~> 3.9"

gem "rails", "~> 8.1"

gem "sqlite3", "~> 2.8"
